### ISSUE TITLE
change background-color

### ISSUE THREAD

**Issue by dennishenning** [silviokennecke/ha-custom-components#1]
Hi @silviokennecke ,

is it possible to use the background color of my theme instead of the color which comes from the card?

![image](https://github.com/silviokennecke/ha-custom-components/assets/57574194/f89dbe46-ea2d-487a-a102-0d556c4a0e1b)

Best
Dennis

**Comment by silviokennecke** [comment]
Hi @dennishenning , the easiest way for now would probably be to add some custom css which overrides the colors. But I will check what I could do here.

**Comment by dennishenning** [comment]
Hi @silviokennecke, 
I found a workaround by manually changing the cards background color to the color of my theme:
![image](https://github.com/silviokennecke/ha-custom-components/assets/57574194/78f8242d-2ce2-4ecf-bd91-f115c951ffcd)

It would be nice if the background color changes automatically when changing the theme in home assistant.

**Comment by silviokennecke** [comment]
I had a lot to do over the last few weeks. I just updated the card. You can now use the `theme` config to select if the theme's default should be used or the Deutsche Bahn theme. Take a look into the documentation for further information about that (https://github.com/silviokennecke/ha-custom-components/wiki/Components#configuration-reference).
