### ISSUE TITLE
Make it functional via hacs please

### ISSUE THREAD

**Issue by kaystrobach** [silviokennecke/ha-custom-components#3]
While i like your repo, i would love to see that easily installable via hacs.

**Comment by silviokennecke** [comment]
Hi @kaystrobach, I'm sorry I did not respond. I was very busy in the last weeks.
I just added the metadata for hacs. You can now add this repository in hacs.

[![Open your Home Assistant instance and open a repository inside the Home Assistant Community Store.](https://my.home-assistant.io/badges/hacs_repository.svg)](https://my.home-assistant.io/redirect/hacs_repository/?owner=silviokennecke&repository=ha-custom-components&category=plugin)

**Comment by kaystrobach** [comment]
No need to be sorry. Thanks a lot. 🎉😊
